"""Export the trained disease classifier as a small JavaScript file for offline use.

    python export_model_js.py

Writes ../static/pwa/model-data.js. Run it again whenever the model is retrained.

The browser re-implements the model directly (one-hot + scaling + logistic regression
+ temperature calibration), so this only works while the model has that shape. Anything
else (for example a random forest) stops here with an error instead of exporting a model
that would silently give different answers; that would need ONNX instead.
"""
import json
from pathlib import Path

import joblib
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder, StandardScaler

ROOT = Path(__file__).resolve().parent
MODEL = ROOT / "models" / "disease_classifier.joblib"
OUT = ROOT.parent / "static" / "pwa" / "model-data.js"


def main():
    b = joblib.load(MODEL)
    pipe = b["pipeline"]
    pre, clf = pipe.named_steps["preprocess"], pipe.named_steps["classifier"]

    assert isinstance(pre, ColumnTransformer) and isinstance(clf, LogisticRegression), \
        "Model is not ColumnTransformer + LogisticRegression; use ONNX for this model."
    assert [n for n, _, _ in pre.transformers_ if n != "remainder"] == ["categorical", "numeric"], \
        "Unexpected preprocessing layout."
    _, cat_pipe, cat_cols = pre.transformers_[0]
    _, num_pipe, num_cols = pre.transformers_[1]
    onehot, scaler = cat_pipe.named_steps["onehot"], num_pipe.named_steps["scale"]
    assert isinstance(onehot, OneHotEncoder) and isinstance(scaler, StandardScaler)
    assert clf.coef_.shape == (len(clf.classes_), len(onehot.get_feature_names_out()) + len(num_cols))
    # The inputs are validated as complete before prediction, so the imputers never fire
    # and are not exported. (predict_disease.py rejects missing values.)

    data = {
        "schema_version": b["schema_version"],
        "classes": list(b["classes"]),                       # output order used by the app
        "temperature": float(b["temperature"]),
        "categorical": [{"name": c, "categories": [str(x) for x in cats]}
                        for c, cats in zip(cat_cols, onehot.categories_)],
        "numeric": [{"name": c, "mean": float(m), "scale": float(s)}
                    for c, m, s in zip(num_cols, scaler.mean_, scaler.scale_)],
        "classifier_classes": [str(c) for c in clf.classes_],  # row order of coef
        "coef": clf.coef_.tolist(),
        "intercept": clf.intercept_.tolist(),
    }
    OUT.write_text(
        "// GENERATED by ml_package/export_model_js.py from models/disease_classifier.joblib. Do not edit.\n"
        "self.GV_MODEL = " + json.dumps(data, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({OUT.stat().st_size / 1024:.1f} KB): {len(num_cols)} numeric + "
          f"{sum(len(c['categories']) for c in data['categorical'])} one-hot columns, {len(clf.classes_)} classes")


if __name__ == "__main__":
    main()
